import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Nostalgic Laboratory",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
